language: node_js
node_js:
  - "11"
dist: trusty
sudo: false

branches:
  only:
  - master

install:
  - git clone -–-depth 1 https://github.com/Jermolene/TiddlyWiki5.git
  - cd TiddlyWiki5
  - npm link
  - cd ..

script:
  - tiddlywiki --–verbose --–build index
  # - mv ./output/index.html ./wiki.html
  # - mv ./output/index.html ./tiddly.html
  - tiddlywiki ---build tiddlyjam
  # - mv ./tiddly.html ./output/tiddly.html
  - echo "tiddlyjam.com" > ./output/CNAME


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_TIDDLYJAM_TEST # Set in the settings page of your repository, as a secure variable
  local_dir: output
  on:
    branch: master